apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "barkuni-app.fullname" . }}
  labels:
    app: {{ include "barkuni-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "barkuni-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "barkuni-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      nodeSelector: {{ toYaml .Values.nodeSelector }}
      tolerations: {{ .Values.tolerations }}
      affinity: {{ toYaml .Values.affinity }}
