apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "barkuni-app.fullname" . }}
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "barkuni-app.fullname" . }}
                port:
                  number: 80
